/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : IDL.Text,
  'bedrooms' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'propertyAddress' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitEnquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : IDL.Text,
    'bedrooms' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'propertyAddress' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitEnquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };